theme: jekyll-theme-leap-day
title: Welcome to the olivynn's homepage!
description: This is my first GitHub page for our DVVS lessons.
<a target="_blank" href="https://calendar.google.com/event?action=TEMPLATE&amp;tmeid=MWplMWJyMDh0cHV0MmI3ZHBiZTA3djNkOGIgdnlubnljaHVrb2xoYUBt&amp;tmsrc=vynnychukolha%40gmail.com"><img border="0" src="https://www.google.com/calendar/images/ext/gc_button1_uk.gif"></a>
